#!/usr/bin/env bash
# Installs nginx and configurates it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
