#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/${replace}/" /etc/nginx/sites-available/default
sudo service nginx restart
