#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get install -y haproxy
server1 = "4465-web-01 3.84.114.176"
server2 = "4465-web-02 3.82.38.127"
frontend = "\nfrontend myfrontend\n\tbind 0.0.0.0:80\n\tdefault_backend myservers\n"
backend = "\nbackend myservers\n\tbalance roundrobin\n\tserver ${server1} check\n\tserver ${server2} check\n"
printf "${frontend} | sudo tee -a /etc/haproxy/haproxy.cfg
printf "${backend} | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
