#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
apt-get -y update
apt-get -y install nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo pkill -1 nginx
